//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.Resource {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Store.Resource.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string StoreLabel {
            get {
                return ResourceManager.GetString("StoreLabel", resourceCulture);
            }
        }
        
        internal static string InfoLabel {
            get {
                return ResourceManager.GetString("InfoLabel", resourceCulture);
            }
        }
        
        internal static string StartButton {
            get {
                return ResourceManager.GetString("StartButton", resourceCulture);
            }
        }
        
        internal static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        internal static string MostPopular {
            get {
                return ResourceManager.GetString("MostPopular", resourceCulture);
            }
        }
        
        internal static string TodaysDeals {
            get {
                return ResourceManager.GetString("TodaysDeals", resourceCulture);
            }
        }
        
        internal static string LatestTechnology {
            get {
                return ResourceManager.GetString("LatestTechnology", resourceCulture);
            }
        }
        
        internal static string iPhone {
            get {
                return ResourceManager.GetString("iPhone", resourceCulture);
            }
        }
        
        internal static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        internal static string Laptop {
            get {
                return ResourceManager.GetString("Laptop", resourceCulture);
            }
        }
        
        internal static string PreOwned {
            get {
                return ResourceManager.GetString("PreOwned", resourceCulture);
            }
        }
        
        internal static string RelevanceButton {
            get {
                return ResourceManager.GetString("RelevanceButton", resourceCulture);
            }
        }
        
        internal static string FiltersButton {
            get {
                return ResourceManager.GetString("FiltersButton", resourceCulture);
            }
        }
    }
}
